dependencies:

  - name: config-init
    repository: file://charts/config-init
    
  - name: keyrotation
    repository: file://charts/keyrotation
    
  - name: oxpassport
    repository: file://charts/oxpassport
    import-values:
      - child: service
        parent: global.oxpassport
    
  - name: opendj
    repository: file://charts/opendj
    version: 1.0.0
    condition: opendj.enabled
    import-values:
      - child: service
        parent: global.ldap
    
  - name: oxauth
    repository: file://charts/oxauth
    version: 1.0.0
    import-values:
      - child: service
        parent: global.oxauth
      
  - name: oxshibboleth
    repository: file://charts/oxshibboleth
    
  - name: oxtrust
    repository: file://charts/oxtrust
    import-values:
      - child: service
        parent: global.oxtrust