global:
  imageRegistry: docker.io
  namespace: default

  # Options: consul or kubernetes
  configAdapter: kubernetes
  
  # the name of some kind of configmap
  configMapName: gluu
  
  consul:
    enabled: false # whether or not to have this chart create the consul server
    host: consul
    port: 8500
    scheme: http # options: http or https
    verify: false # options: true or false
    consistency: stale # options: default, stale, consistent
    # tlsSecretName: consul-tls-secret
    
  ## An array of available ldap hosts to use
  ldap:
    # options: opendj or openldap
    type: opendj
    enabled: true # whether or not to have this chart create the LDAP server
    extraHosts: [] # array of k,v like so: host: somehost, port: someport
      
  persistence:
    enabled: true
    volumes:
      sharedShib:
        enabled: true
        name: shared-shib
        size: 8Gi
        storageClass: "-"
        # existingClaim: "-"
        accessModes:
          - ReadWriteOnce
        provisioner:
          enabled: false
          type: hostPath
          spec:
            path: "/oxtrust/shared-shib"
  
keyrotation:
  interval: 2
  check: 3600
  
# oxauth:
  # maxRamFraction: 
  # debugPort: 
  
config-init:
  orgName: k8s
  adminPass: password
  email: k8s@email.com
  domain: localhost
  country: US
  state: UT
  city: SLC

opendj:  
  enabled: true
  init: true
  enableTLS: false # does nothing yet
  oxtrustConfigGen: true
  cacheType: IN_MEMORY
  redis:
    type: STANDALONE
    host: redis
    port: 6379