apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ template "gluu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "gluu.name" . }}
      chart: {{ template "gluu.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "gluu.name" . }}
        chart: {{ template "gluu.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "gluu.fullname" . }}
        image: "{{ template "gluu.image" . }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        env:
        - name: GLUU_KV_HOST
          value: gluuconsul
        - name: GLUU_KV_PORT
          value: "8500"
        - name: GLUU_LDAP_URL
          value: openldap-svc:1389
        ports:
        - containerPort: 8080
          protocol: TCP