apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  serviceName: {{ template "gluu.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "gluu.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "gluu.labels" . | indent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases: 
{{ toYaml .Values.hostAliases | indent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.affinity }}
      affinity: 
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
        - name: {{ template "gluu.fullname" . }}
          imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
          image: "{{ template "gluu.image" . }}"
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GLUU_OXAUTH_BACKEND
              value: {{ (printf "%s-oxauth:%.f" .Release.Name .Values.global.oxauth.port) | quote }}
            - name: GLUU_SHIB_SOURCE_DIR
              value: "/opt/shibboleth-idp"
            - name: GLUU_SHIB_TARGET_DIR
              value: "/opt/shared-shibboleth-idp"
            {{- if .Values.maxRamFraction }}
            - name: GLUU_MAX_RAM_FRACTION
              value: {{ .Values.maxRamFraction | quote }}
            {{- end }}
            {{- if .Values.debugPort }}
            - name: GLUU_DEBUG_PORT
              value: {{ .Values.debugPort | quote }}
            {{- end }}
            - name: GLUU_LDAP_URL
              value: "{{ template "gluu.ldaplist" . }}"
{{ include "gluu.commonvars" . | indent 12 }}
          volumeMounts:
            # name must match the volume name below
            - name: shared-shib
              mountPath: "/opt/shared-shibboleth-idp"
            - name: logs
              mountPath: /opt/gluu/jetty/identity/logs
            - name: lib-ext
              mountPath: /opt/gluu/jetty/identity/lib/ext
            - name: custom-static
              mountPath: /opt/gluu/jetty/identity/custom/static
            - name: custom-pages
              mountPath: /opt/gluu/jetty/identity/custom/pages
          livenessProbe:
            httpGet:
              path: /identity/restv1/scim-configuration
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /identity/restv1/scim-configuration
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 25
      volumes: []
  volumeClaimTemplates:
    
    {{ $sharedShib := .Values.global.persistence.volumes.sharedShib }}
    - metadata:
        name: shared-shib
        labels:
          volume: shared-shib
{{ include "gluu.labels" . | indent 10 }}
      spec:
        accessModes:
        {{- range $sharedShib.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $sharedShib.size | quote }}
        storageClassName: {{ template "gluu.storageClass" $sharedShib }}
      {{- if and $sharedShib.provisioner.enabled (not $sharedShib.existingClaim) }}
        selector:
          matchLabels: 
            volume: shared-shib
{{ include "gluu.labels" . | indent 12 }}
      {{- end }}
      
    {{ $oxtrustLogs := .Values.persistence.volumes.logs }}
    - metadata:
        name: logs
        labels:
          volume: logs
{{ include "gluu.labels" . | indent 10 }}
      spec:
        accessModes:
        {{- range $oxtrustLogs.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $oxtrustLogs.size | quote }}
        storageClassName: {{ template "gluu.storageClass" $oxtrustLogs }}
      {{- if and $oxtrustLogs.provisioner.enabled (not $oxtrustLogs.existingClaim) }}
        selector:
          matchLabels: 
            volume: logs
{{ include "gluu.labels" . | indent 12 }}
      {{- end }}
      
    {{ $libExt := .Values.persistence.volumes.libExt }}
    - metadata:
        name: lib-ext
        labels:
          volume: lib-ext
{{ include "gluu.labels" . | indent 10 }}
      spec:
        accessModes:
        {{- range $libExt.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $libExt.size | quote }}
        storageClassName: {{ template "gluu.storageClass" $libExt }}
      {{- if and $libExt.provisioner.enabled (not $libExt.existingClaim) }}
        selector:
          matchLabels: 
            volume: lib-ext
{{ include "gluu.labels" . | indent 12 }}
      {{- end }}
      
    {{ $customStatic := .Values.persistence.volumes.customStatic }}
    - metadata:
        name: custom-static
        labels:
          volume: custom-static
{{ include "gluu.labels" . | indent 10 }}
      spec:
        accessModes:
        {{- range $customStatic.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $customStatic.size | quote }}
        storageClassName: {{ template "gluu.storageClass" $customStatic }}
      {{- if and $customStatic.provisioner.enabled (not $customStatic.existingClaim) }}
        selector:
          matchLabels: 
            volume: custom-static
{{ include "gluu.labels" . | indent 12 }}
      {{- end }}
      
    {{ $customPages := .Values.persistence.volumes.customPages }}
    - metadata:
        name: custom-pages
        labels:
          volume: custom-pages
{{ include "gluu.labels" . | indent 10 }}
      spec:
        accessModes:
        {{- range $customPages.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $customPages.size | quote }}
        storageClassName: {{ template "gluu.storageClass" $customStatic }}
      {{- if and $customPages.provisioner.enabled (not $customPages.existingClaim) }}
        selector:
          matchLabels: 
            volume: custom-pages
{{ include "gluu.labels" . | indent 12 }}
      {{- end }}
      