apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "gluu.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  serviceName: {{ template "gluu.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "gluu.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "gluu.labels" . | indent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases: 
{{ toYaml .Values.hostAliases | indent 8 }}
      {{- end }}
            {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.affinity }}
      affinity: 
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
        - name: oxtrust
          imagePullPolicy: Always
          image: gluufederation/oxtrust:3.1.4_01
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GLUU_OXAUTH_BACKEND
              value: {{ printf "%s-oxauth:%s" .Release.Name "8080" }}
            - name: GLUU_SHIB_SOURCE_DIR
              value: '/opt/shibboleth-idp'
            - name: GLUU_SHIB_TARGET_DIR
              value: '/opt/shared-shibboleth-idp'
            {{- if .Values.maxRamFraction }}
            - name: GLUU_MAX_RAM_FRACTION
              value: {{ .Values.maxRamFraction }}
            {{- end }}
            {{- if .Values.debugPort }}
            - name: GLUU_DEBUG_PORT
              value: {{ .Values.debugPort }}
            {{- end }}
            - name: GLUU_LDAP_URL
              value: "{{ template "gluu.ldaplist" .Values.global.ldap }}"
{{ include "gluu.commonvars" . | indent 12 }}
          volumeMounts:
            # name must match the volume name below
            - name: shared-shib
              mountPath: "/opt/shared-shibboleth-idp"
            - name: oxtrust-logs
              mountPath: /opt/gluu/jetty/identity/logs
            - name: oxtrust-lib-ext
              mountPath: /opt/gluu/jetty/identity/lib/ext
            - name: oxtrust-custom-static
              mountPath: /opt/gluu/jetty/identity/custom/static
            - name: oxtrust-custom-pages
              mountPath: /opt/gluu/jetty/identity/custom/pages
          livenessProbe:
            httpGet:
              path: /identity/restv1/scim-configuration
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /identity/restv1/scim-configuration
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 25
      volumes:
        - name: shared-shib
          persistentVolumeClaim:
            claimName: shared-shib-volume-claim
        - name: oxtrust-logs
          persistentVolumeClaim:
            claimName: oxtrust-logs-volume-claim
        - name: oxtrust-lib-ext
          persistentVolumeClaim:
            claimName: oxtrust-lib-ext-volume-claim
        - name: oxtrust-custom-static
          persistentVolumeClaim:
            claimName: oxtrust-custom-static-volume-claim
        - name: oxtrust-custom-pages
          persistentVolumeClaim:
            claimName: oxtrust-custom-pages-volume-claim
  volumeClaimTemplates:
    