apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "gluu.fullname" . }}-generate
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
{{ include "gluu.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if .Values.affinity }}
      affinity: 
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ template "gluu.fullname" . }}-config
      containers:
        - name: {{ template "gluu.fullname" . }}
          image: "{{ template "gluu.image" . }}"
          volumeMounts:
            - name: config
              mountPath: /opt/config-init/db/
          env:
{{ include "gluu.commonvars" . | indent 12 }}            
            - name: ADMIN_PW
              value: {{ .Values.adminPass }}
            - name: EMAIL
              value: {{ .Values.email }}
            - name: DOMAIN
              value: {{ .Values.domain  }}
            - name: ORG_NAME
              value: {{ .Values.orgName }}
            - name: COUNTRY_CODE
              value: {{ .Values.country }}
            - name: STATE
              value: {{ .Values.state }}
            - name: CITY
              value: {{ .Values.city }}
            - name: LDAP_TYPE
              value: {{ .Values.global.ldap.type }}
          command: [
            "python", "/opt/config-init/scripts/entrypoint.py", "generate", 
            "--admin-pw", "$(ADMIN_PW)", 
            "--email", "$(EMAIL)", 
            "--domain", "$(DOMAIN)", 
            "--org-name", "$(ORG_NAME)", 
            "--country-code", "$(COUNTRY_CODE)", 
            "--state", "$(STATE)", 
            "--city", "$(CITY)", 
            "--ldap-type", "$(LDAP_TYPE)"
          ]