kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "gluu.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
rules:
  - apiGroups: [""] # "" refers to the core API group
    resources: [
      "services", 
      "endpoints", 
      "configmaps"
    ]
    verbs: [
      "get", 
      "list", 
      "watch", 
      "create", 
      "update", 
      "patch", 
      "delete"
    ]