apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "gluu.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "gluu.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.http.nodePort))) }}
      nodePort: {{ .Values.service.http.nodePort }}
{{- end }}
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.https.nodePort))) }}
      nodePort: {{ .Values.service.https.nodePort }}
{{- end }}
  selector:
{{ include "gluu.labels" . | indent 4 }}