apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gluuoxauth
    env: dev
  name: gluuoxauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluuoxauth
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gluuoxauth
        env: dev
    spec:
      containers:
      - env:
        - name: GLUU_KV_HOST
          value: gluuconsul
        - name: GLUU_KV_PORT
          value: "8500"
        - name: GLUU_LDAP_URL
          value: openldap-svc:1389
        image: gluufederation/oxauth:3.1.1_dev
        imagePullPolicy: IfNotPresent
        name: gluuoxauth
        ports:
        - containerPort: 8080
          protocol: TCP