# how many replications are needed
replicas: 1

## Used in conjunction with Docker memory limitations (docker run -m <mem>) to identify the fraction of the maximum amount of heap memory you want the JVM to use.
# maxRamFraction: 

## port of remote debugging (if omitted, remote debugging will be disabled).
# debugPort: 

## keyrotation image version
## ref: https://hub.docker.com/r/bitnami/redis/tags/
##
image:
  registry: docker.io
  repository: gluufederation/oxauth
  ## Gluu image tag
  ##
  tag: 3.1.4_01
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

## Tweak the available pod resources  
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
# resources:
#   requests:
#     memory: 256Mi
#     cpu: 100m

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
# nodeSelector: {}

## Pods affinity/anti-affinity i.e. fancy way of doing nodeSelector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
# affinity: {}

## Pod tolerations
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
# tolerations: []

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## pod Annotation and Labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
# podAnnotations: {}

## extra pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
# podLabels: {}

service:
  # annotations: {}
  clusterIP: ""

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  port: 8080
  type: ClusterIP
  nodePort: 30808
  
persistence:
  enabled: true
  volumes:
    logs:
      enabled: true
      name: logs
      size: 8Gi
      storageClass: "-"
      # existingClaim: "-"
      accessModes:
        - ReadWriteOnce
      provisioner:
        enabled: false
        type: hostPath
        spec:
          path: "/oxtrust/logs"
    libExt:
      enabled: true
      name: lib-ext
      size: 8Gi
      storageClass: "-"
      # existingClaim: "-"
      accessModes:
        - ReadWriteOnce
      provisioner:
        enabled: false
        type: hostPath
        spec:
          path: "/oxtrust/lib-ext"
    customStatic:
      enabled: true
      name: custom-static
      size: 8Gi
      storageClass: "-"
      # existingClaim: "-"
      accessModes:
        - ReadWriteOnce
      provisioner:
        enabled: false
        type: hostPath
        spec:
          path: "/oxtrust/custom-static"
    customPages:
      enabled: true
      name: custom-pages
      size: 8Gi
      storageClass: "-"
      # existingClaim: "-"
      accessModes:
        - ReadWriteOnce
      provisioner:
        enabled: false
        type: hostPath
        spec:
          path: "/oxtrust/custom-pages"